version: "3"
networks:
  nginx:
    external: false
services:
  rabbitmq:
    restart: "no"
  redis:
    restart: "no"
  postgres:
    restart: "no"
  celery:
    restart: "no"
  flask:
    restart: "no"
    volumes:
      - ./yyy:/home/app
    ports:
      - "5000:80"
    command: sleep 999999999