version: "3"
networks:
  nginx:
    external: true
volumes:
  yyy_postgres_data:
services:
  rabbitmq:
    image: rabbitmq:3
    restart: always
    ports:
      - "5672"
    container_name: yyy-rabbitmq
  redis:
    image: redis
    container_name: yyy-redis
    ports:
      - "6379"
    restart: always
  postgres:
    image: postgres:9.5
    container_name: yyy-postgres
    ports:
      - "5432"
    restart: always
    volumes:
      - yyy_postgres_data:/var/lib/postgresql/data
  celery:
    image: nathanielobrown/yyy
    container_name: yyy-celery
    restart: always
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - BROKER_NAME=yyy-rabbitmq
      - BACKEND_NAME=yyy-redis
      - DB_CONN_STR=postgresql+psycopg2://postgres@yyy-postgres:5432
    command: >
      celery -A app.celery worker --loglevel=info -P
      eventlet --max-memory-per-child 40000 --concurrency 20
  flask:
    image: nathanielobrown/yyy
    networks:
      default:
      nginx:
        aliases:
          - boat-search
          - yachtsyachtsyachts.com
    restart: always
    container_name: yachtsyachtsyachts.com
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "80"
    environment:
      - BROKER_NAME=yyy-rabbitmq
      - BACKEND_NAME=yyy-redis
      - DB_CONN_STR=postgresql+psycopg2://postgres@yyy-postgres:5432
    command: >
      uwsgi --http :80 --manage-script-name
      --mount /=app:app --workers 2 --threads 4
